services:
  filebrowser:
    hostname: filebrowser
    restart: unless-stopped
    build: .
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
    volumes:
      - $PWD/config/antizapret/custom:/srv
    depends_on:
      - antizapret
